[package]
name = "default-components"
version = "0.1.0"
edition = "2024"


[dependencies]
api-types = { workspace = true, features = ["server-support"] }
axum = { workspace = true, features = ["ws"] }
chrono.workspace = true
serde.workspace = true
server.workspace = true
tokio.workspace = true
tracing.workspace = true
utils.workspace = true
reqwest = "0.13"
serde_json = "1"
minecraft-net = "0.1.0"
lettre = "0.11"
